version: "3.9"
name: multiuserapp

services:

  api:
    build:
      context: ./my_daily_todos_app
      dockerfile: Dockerfile.dev
    volumes:
      - ./my_daily_todos_app:/code  # Sync local development directory with the container
    depends_on:
        - postgres_db
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000  

  postgres_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: PostgresCont
    environment:
        - POSTGRES_USER=hussain
        - POSTGRES_PASSWORD=mypassword
        - POSTGRES_DB=mydatabase
    ports:
        - '5433:5432'
    volumes:
        - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local

networks:
  default:
    driver: bridge