name: "online_auth_class"

services:
  oauth-api-service:
    image: "auth-api-img"
    build:
      context: ./oauth2-authentication
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./oauth-service:/code
    networks:
      - oauth-network

networks:
  oauth-network:
    